### ISSUE TITLE
Unofficial XING API reference

### ISSUE THREAD

**Issue by itsalicelee** [l4rm4nd/XingDumper#1]
Hi! Thank you for developing a useful project for job searching and recruiting. 
Would you mind share the reference to the unofficial API (`https://www.xing.com/xing-one/api`) documentation that you are using? Thank you!

**Comment by l4rm4nd** [comment]
Did not use any public api documentation. Unsure whether one exists at all for the API used.

It's basically reverse engineered by using an HTTP intercepting proxy and parsing the JSON results properly. See code for details.
